# Generated by Django 3.1 on 2020-09-23 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_change_field_of_time'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='seminars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='seminar.seminar'),
        ),
    ]
