# Generated by Django 3.1 on 2020-09-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200923_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantprofile',
            old_name='seminars',
            new_name='seminar',
        ),
    ]
