# Generated by Django 3.1 on 2020-10-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_year_blank_True'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='seminar',
        ),
    ]
