# Generated by Django 3.1 on 2020-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_seminar_field_in_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='university',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
