# Generated by Django 3.1 on 2020-11-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alloww_blank_at_company_year_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
