# Generated by Django 3.1 on 2020-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='seminars',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='seminar',
            name='time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
        migrations.DeleteModel(
            name='ParticipantProfile',
        ),
    ]
