# Generated by Django 3.1 on 2020-09-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_change_field_of_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseminar',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
