# Generated by Django 3.1 on 2020-11-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_add_constraints_for_minvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userseminar',
            name='joined_at',
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='role',
            field=models.CharField(choices=[('participant', 'participant'), ('participant', 'instructor')], db_index=True, max_length=50),
        ),
    ]
